<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HP-15s-fq2535TU" ignored="0" name="Default test" tests="2" failures="1" timestamp="2021-06-14T00:42:54 IST" time="149.13" errors="0">
  <testcase name="runScenario" time="51.701" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at StepDefinitions.MakeMyTripStepDefinition.validating_of(MakeMyTripStepDefinition.java:256)
at âœ½.Validating "10-7-2021", returndate of "oneway"(file:///C:/Users/USER/Downloads/hrcassignment4/src/test/java/Features/MakeMyTrip.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="97.073" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Default test -->
